# upstream definitions
upstream portainer_upstream {
  server portainer:9000;
}

upstream dozzle_upstream {
  server dozzle:8080;
}

server {
  listen 443 ssl default_server;
  server_name _;

  ssl_certificate /etc/nginx/ssl/tools.crt;
  ssl_certificate_key /etc/nginx/ssl/tools.key;

  # Debug endpoint to confirm server block in use
  location = /ping {
    return 200 'pong';
  }

  # Ensure trailing slash
  location = /portainer {
    return 301 /portainer/;
  }

  # Portainer
  location /portainer/ {
  # Normalize the path so upstream sees it without the /portainer prefix
  rewrite ^/portainer(/.*)$ $1 break;
    auth_basic "Restricted";
  auth_basic_user_file /etc/nginx/.htpasswd;
  proxy_pass http://portainer_upstream/;
    proxy_redirect off;
    proxy_http_version 1.1;
  proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header Authorization "";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Prefix /portainer;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

  # Ensure trailing slash
  location = /dozzle {
    return 301 /dozzle/;
  }

  # Dozzle
  location /dozzle/ {
    auth_basic "Restricted";
  auth_basic_user_file /etc/nginx/.htpasswd;
  proxy_pass http://dozzle_upstream;
    proxy_redirect off;
    proxy_http_version 1.1;
  proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header Authorization "";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Prefix /dozzle;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
