#!/usr/bin/env python3
"""Compare the live Solar tab (sidebar "Solar", /dashboard-solar) with the Site solar seed.

The Solar tab is a storage dashboard that exists only in the live Home Assistant
(it was built from MQTT discovery and edited by ha_label_*.py), so it is not in git.
Export it read-only first, on .105:

  HA_TOKEN_FILE=~/.ha_token python3 scripts/site_solar_settings.py export-dashboard

Then compare it with config/dashboards/solar-plant.yaml (read-only by default):

  python3 scripts/compare_solar_tab.py config/dashboards/exports/solar-tab.json
  python3 scripts/compare_solar_tab.py EXPORT --markdown /tmp/solar-tab-table.md
  python3 scripts/compare_solar_tab.py EXPORT --apply        # add the missing cards

Cards are compared by what they show (their entity ids), not by YAML. Each Solar card is:

  on-site-solar   every entity already has a live card or badge on Site solar
  history-only    its entities are on Site solar only inside History graphs
  partly          some entities are on Site solar, some are not
  missing         none of its entities are on Site solar
  same-content    no entities, and an identical card already exists on Site solar
  no-entities     no entities and no identical card (markdown, sankey, ...): review
  needs-decision  shows H5082 plugs or dump helpers. Site solar requires a help card and
                  a doc for those boxes, and never hard-coded plug names, so --apply
                  does not copy them; decide by hand.

--apply appends ONE new view (title "Solar tab", path "solar-tab") at the end of
the seed with the missing / history-only / partly (missing entities only) /
no-entities cards, grouped under the Solar tab's own headings. Existing views are not
touched (the script checks this). Re-running --apply replaces only that generated view.
"""

from __future__ import annotations

import argparse
import copy
import fnmatch
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SEED = ROOT / "config" / "dashboards" / "solar-plant.yaml"
NEW_VIEW_TITLE = "Solar tab"
NEW_VIEW_PATH = "solar-tab"
MARKER = "  # --- generated by scripts/compare_solar_tab.py --apply (Solar tab cards not on Site solar) ---"

DOMAINS = (
    "sensor|binary_sensor|switch|input_text|input_select|input_number|input_boolean|input_button|"
    "input_datetime|number|select|timer|weather|climate|camera|image|light|button|automation|script|"
    "sun|person|device_tracker|update|fan|cover|lock|media_player|counter|text|event|zone|water_heater|"
    "valve|vacuum|siren|alarm_control_panel|humidifier|todo|calendar|scene|group"
)
ENTITY_RE = re.compile(rf"\b(?:{DOMAINS})\.[a-z0-9_]+(?:\*[a-z0-9_*]*)?")
CONTAINERS = ("vertical-stack", "horizontal-stack", "grid")
LIST_TYPES = ("entities", "glance", "history-graph", "statistics-graph", "logbook", "map")
LIVE = "live"
HISTORY = "history"
PLUG_OR_DUMP = re.compile(r"h5082|ihoment|\bdump_|\.dump_")


@dataclass
class Card:
    view: str
    section: str
    card: dict[str, Any]
    kind: str = "card"  # card | badge
    entities: list[str] = field(default_factory=list)

    @property
    def label(self) -> str:
        return str(self.card.get("type", "entity" if self.kind == "badge" else "?"))


def load_config(path: Path) -> dict[str, Any]:
    """A Lovelace config from JSON (export wrapper or raw) or YAML."""
    text = path.read_text(encoding="utf-8")
    data = json.loads(text) if path.suffix == ".json" else yaml.safe_load(text)
    if isinstance(data, dict) and isinstance(data.get("config"), dict):
        data = data["config"]
    if not isinstance(data, dict) or not isinstance(data.get("views"), list):
        raise SystemExit(f"{path}: not a Lovelace config with views")
    return data


def entities_of(node: Any) -> list[str]:
    """Entity ids a card shows: entity / entities keys plus ids named in text
    (templates, markdown, auto-entities filters). Globs keep their '*'."""
    found: list[str] = []

    def add(value: str) -> None:
        for match in ENTITY_RE.findall(value):
            if match not in found:
                found.append(match)

    def walk(n: Any) -> None:
        if isinstance(n, dict):
            for key, value in n.items():
                if key in ("card_mod", "styles", "exclude"):  # excluded = not shown
                    continue
                walk(value)
        elif isinstance(n, list):
            for value in n:
                walk(value)
        elif isinstance(n, str):
            add(n)

    walk(node)
    return found


def _heading(card: dict[str, Any]) -> str | None:
    if card.get("type") == "heading":
        return str(card.get("heading") or "")
    return None


def iter_cards(config: dict[str, Any]) -> list[Card]:
    """Every leaf card (containers opened) and badge, with its view / heading."""
    out: list[Card] = []

    def leaf(view: str, section: str, card: dict[str, Any]) -> None:
        if card.get("type") in CONTAINERS and isinstance(card.get("cards"), list):
            for inner in card["cards"]:
                if isinstance(inner, dict):
                    leaf(view, section, inner)
            return
        if card.get("type") == "conditional" and isinstance(card.get("card"), dict):
            leaf(view, section, card["card"])
            return
        out.append(Card(view, section, card, "card", entities_of(card)))

    for index, view in enumerate(config.get("views") or []):
        vname = str(view.get("title") or view.get("path") or f"view {index}")
        for raw in view.get("badges") or []:
            badge = {"entity": raw} if isinstance(raw, str) else raw
            out.append(Card(vname, "(badges)", badge, "badge", entities_of(badge)))
        for sidx, section in enumerate(view.get("sections") or []):
            sname = f"section {sidx + 1}"
            for card in section.get("cards") or []:
                if not isinstance(card, dict):
                    continue
                head = _heading(card)
                if head is not None:
                    sname = head or sname
                    continue
                leaf(vname, sname, card)
        for card in view.get("cards") or []:  # masonry / panel views
            if isinstance(card, dict):
                leaf(vname, "(cards)", card)
    return out


@dataclass
class SiteIndex:
    where: dict[str, list[tuple[str, str]]]  # entity -> [(kind, "View > Heading (type)")]
    globs: list[tuple[str, str, str]]  # (pattern, kind, where)
    contents: list[str]  # json of cards without entities, for same-content checks

    def locate(self, entity: str) -> list[tuple[str, str]]:
        hits = list(self.where.get(entity, []))
        hits += [(kind, where) for pattern, kind, where in self.globs if fnmatch.fnmatch(entity, pattern)]
        return hits


def site_index(config: dict[str, Any]) -> SiteIndex:
    where: dict[str, list[tuple[str, str]]] = {}
    globs: list[tuple[str, str, str]] = []
    contents: list[str] = []
    for card in iter_cards(config):
        kind = HISTORY if card.card.get("type") in ("history-graph", "statistics-graph") else LIVE
        place = f"{card.view} > {card.section} ({card.label})"
        if not card.entities:
            contents.append(_content_key(card.card))
        for entity in card.entities:
            if "*" in entity:
                globs.append((entity, kind, place))
            else:
                where.setdefault(entity, []).append((kind, place))
    return SiteIndex(where, globs, contents)


def _content_key(card: dict[str, Any]) -> str:
    clean = {k: v for k, v in card.items() if k not in ("grid_options", "view_layout", "layout_options")}
    return json.dumps(clean, sort_keys=True)


@dataclass
class Row:
    card: Card
    status: str
    where: list[str]
    missing: list[str]


def _status(live: list[str], hist: list[str], missing: list[str]) -> str:
    if not missing and not hist:
        return "on-site-solar"
    if not missing and not live:
        return "history-only"
    if not live and not hist:
        return "missing"
    return "partly"


def classify(solar: dict[str, Any], site: dict[str, Any]) -> list[Row]:
    index = site_index(site)
    rows: list[Row] = []
    for card in iter_cards(solar):
        ents = [e for e in card.entities if "*" not in e]
        blob = json.dumps(card.card)
        if PLUG_OR_DUMP.search(blob):
            hits = sorted({w for e in ents for _k, w in index.locate(e)})
            rows.append(Row(card, "needs-decision", hits, [e for e in ents if not index.locate(e)]))
            continue
        if not ents:
            same = _content_key(card.card) in index.contents
            rows.append(Row(card, "same-content" if same else "no-entities", [], []))
            continue
        live, hist, missing = [], [], []
        places: list[str] = []
        for entity in ents:
            hits = index.locate(entity)
            kinds = {k for k, _w in hits}
            places += [w for _k, w in hits]
            if LIVE in kinds:
                live.append(entity)
            elif HISTORY in kinds:
                hist.append(entity)
            else:
                missing.append(entity)
        status = _status(live, hist, missing)
        seen: list[str] = []
        for place in places:
            if place not in seen:
                seen.append(place)
        rows.append(Row(card, status, seen, missing + hist))
    return rows


STATUS_ORDER = (
    "on-site-solar",
    "same-content",
    "history-only",
    "partly",
    "missing",
    "no-entities",
    "needs-decision",
)
DECISION = {
    "on-site-solar": "keep as is (already on Site solar)",
    "same-content": "keep as is (identical card on Site solar)",
    "history-only": "add live card to Solar tab view",
    "partly": "add card with only the missing entities",
    "missing": "add to Solar tab view",
    "no-entities": "added for review (no entities to compare)",
    "needs-decision": "not copied: plug / dump box needs help card + doc; decide by hand",
}
ADDED = ("history-only", "partly", "missing", "no-entities")


def summary(rows: list[Row]) -> dict[str, int]:
    counts = {s: 0 for s in STATUS_ORDER}
    for row in rows:
        counts[row.status] += 1
    return counts


def markdown_table(rows: list[Row]) -> str:
    lines = [
        "| # | Solar tab (view > heading) | Card | Entities | Status | On Site solar / decision |",
        "|---|---|---|---|---|---|",
    ]
    for n, row in enumerate(rows, 1):
        ents = ", ".join(f"`{e}`" for e in row.card.entities[:6]) or "-"
        if len(row.card.entities) > 6:  # noqa: PLR2004 - keep the table readable
            ents += f" (+{len(row.card.entities) - 6})"
        where = "; ".join(row.where[:3]) if row.where else ""
        extra = f" Missing: {', '.join(f'`{e}`' for e in row.missing)}." if row.status == "partly" else ""
        note = (where + " - " if where else "") + DECISION[row.status] + extra
        lines.append(
            f"| {n} | {row.card.view} > {row.card.section} | {row.card.label} | {ents} | {row.status} | {note} |"
        )
    counts = summary(rows)
    lines.append("")
    lines.append("Totals: " + ", ".join(f"{k} {v}" for k, v in counts.items() if v))
    return "\n".join(lines) + "\n"


def card_to_add(row: Row) -> dict[str, Any] | None:
    if row.status not in ADDED:
        return None
    if row.card.kind == "badge":
        return {"type": "tile", "entity": row.card.card.get("entity")} if row.card.card.get("entity") else None
    card = copy.deepcopy(row.card.card)
    if row.status == "partly" and card.get("type") in LIST_TYPES and isinstance(card.get("entities"), list):
        keep = set(row.missing)
        card["entities"] = [
            e for e in card["entities"] if (e if isinstance(e, str) else (e or {}).get("entity")) in keep
        ]
    return card


def build_view(rows: list[Row]) -> dict[str, Any] | None:
    groups: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        card = card_to_add(row)
        if card is None:
            continue
        groups.setdefault(row.card.section, []).append(card)
    if not groups:
        return None
    sections = []
    for heading, cards in groups.items():
        title = heading if not heading.startswith("section ") and not heading.startswith("(") else "More"
        sections.append({"type": "grid", "cards": [{"type": "heading", "heading": title}, *cards]})
    intro = {
        "type": "markdown",
        "content": (
            "Cards from the old **Solar** tab that Site solar did not have yet "
            "(added by `scripts/compare_solar_tab.py`). Move or delete them freely."
        ),
    }
    return {
        "title": NEW_VIEW_TITLE,
        "path": NEW_VIEW_PATH,
        "type": "sections",
        "max_columns": 3,
        "sections": [{"type": "grid", "cards": [intro]}, *sections],
    }


class _IndentDumper(yaml.SafeDumper):
    def increase_indent(self, flow: bool = False, indentless: bool = False):  # noqa: ARG002
        return super().increase_indent(flow, False)


def view_yaml(view: dict[str, Any]) -> str:
    text = yaml.dump([view], Dumper=_IndentDumper, sort_keys=False, allow_unicode=True, width=100)
    return "".join(("  " + line if line.strip() else line) for line in text.splitlines(True))


def apply(seed_path: Path, rows: list[Row]) -> str:
    text = seed_path.read_text(encoding="utf-8")
    before = yaml.safe_load(text)
    if MARKER in text:
        text = text[: text.index(MARKER)].rstrip("\n") + "\n"
    elif any(v.get("path") == NEW_VIEW_PATH for v in before["views"]):
        raise SystemExit(f"{seed_path} already has a hand-made view path {NEW_VIEW_PATH!r}; not touching it")
    base = yaml.safe_load(text)
    if list(base)[-1] != "views":
        raise SystemExit(f"{seed_path}: 'views' must be the last top-level key to append safely")
    view = build_view(rows)
    if view is None:
        seed_path.write_text(text, encoding="utf-8")
        return "nothing to add: every Solar tab card is already on Site solar"
    blob = json.dumps(view)
    if re.search(r"(^|[^a-z_])initial:", yaml.dump(view)):
        raise SystemExit("refusing: a copied card contains 'initial:'")
    new_text = text + MARKER + "\n" + view_yaml(view)
    after = yaml.safe_load(new_text)
    kept = [v for v in after["views"] if v.get("path") != NEW_VIEW_PATH]
    old = [v for v in base["views"] if v.get("path") != NEW_VIEW_PATH]
    if kept != old or {k: v for k, v in after.items() if k != "views"} != {
        k: v for k, v in base.items() if k != "views"
    }:
        raise SystemExit("refusing: appending would change existing Site solar views")
    seed_path.write_text(new_text, encoding="utf-8")
    cards = sum(len(s["cards"]) - 1 for s in view["sections"][1:])
    custom = sorted(set(re.findall(r'"type": "(custom:[^"]+)"', blob)))
    note = f" (custom cards: {', '.join(custom)})" if custom else ""
    return f"added view {NEW_VIEW_TITLE!r} (/{NEW_VIEW_PATH}) with {cards} cards{note}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("export", type=Path, help="Solar tab export (JSON from export-dashboard)")
    parser.add_argument("--seed", type=Path, default=SEED)
    parser.add_argument("--markdown", type=Path, help="also write the comparison table here")
    parser.add_argument("--apply", action="store_true", help="append missing cards to the seed")
    args = parser.parse_args(argv)
    solar = load_config(args.export)
    site = load_config(args.seed)
    rows = classify(solar, site)
    table = markdown_table(rows)
    print(table)
    if args.markdown:
        args.markdown.write_text(table, encoding="utf-8")
    if args.apply:
        print(apply(args.seed, rows))
    return 0


if __name__ == "__main__":
    sys.exit(main())
